// Actions Types
export const LOAD_COURSES_SUCCCESS = "LOAD_COURSES_SUCCCESS";
export const LOAD_AUTHORS_SUCCCESS = "LOAD_AUTHORS_SUCCCESS";
export const UPDATE_COURSE_SUCCCESS = "UPDATE_COURSE_SUCCCESS";
export const CREATE_COURSE_SUCCCESS = "CREATE_COURSE_SUCCCESS";
